/**
 *  This header file include some defined macro to cut out
 *  the unused opencl declared lable in the cl files which
 *  is generated by CBackend.
 *
 */

#ifdef QUERIES
#define __global 
#define uintptr_t unsigned int *
#endif
